version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - cd ManualUploadsNotifierFunction/
      - gradle clean build
      - cd ..
      - sam package
        --template-file template.yaml
        --s3-bucket cf-templates-16dsvbtfx7fso-eu-west-2
        --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
