version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - gradle build
      - sam package
        --template-file sam-template.yml
        --s3-bucket cf-templates-16dsvbtfx7fso-eu-west-2
        --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
