version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - gradle build
      - sam package
        --template-file sam-template.yml
        --s3-bucket codepipeline-eu-west-2-418870675604
        --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
