AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template which deploys two functions (manually invoked and automatically triggered).
  Each of the functions does read messages from SQS queue, process them and send appropriate notification to SNS topic.

Globals:
  Function:
    Timeout: 20

Resources:
  ManualUploadsNotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Imageholder-manual-uploads-batch-notifier-2
      Role: arn:aws:iam::423352658953:role/ImageHolderLambdaRole
      Description: Function (manually invoked) which receives messages from SQS queue and sends notification to SNS topic.
      CodeUri: ./ManualUploadsNotifierFunction
      Handler: manual.imageholder.Handler::handleRequest
      Runtime: java11
      MemorySize: 704
      Environment:
        Variables:
          REGION: eu-west-2
          SNS_TOPIC_ARN: arn:aws:sns:eu-west-2:423352658953:eugene-ivanov-training-imageholder-topic
          SQS_QUEUE_NAME: eugene-ivanov-training-imageholder-sqs-queue
          SQS_WAIT_TIME_SECONDS: 5
      Events:
        ManualUploadsNotifier:
          Type: Api
          Properties:
            Path: /uploads-batch-notifier/manually
            Method: post

Outputs:
  ManualUploadsNotifierApi:
    Description: "API Gateway endpoint URL for Prod stage for ManualUploadsNotifier function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/uploads-batch-notifier/manually/"
  ManualUploadsNotifierFunction:
    Description: "ManualUploadsNotifier Lambda Function ARN"
    Value: !GetAtt ManualUploadsNotifierFunction.Arn
  ManualUploadsNotifierFunctionIamRole:
    Description: "Explicit IAM Role defined for ManualUploadsNotifier function"
    Value: !GetAtt ManualUploadsNotifierFunction.Role
